json.id reservation.id
json.inbox_id reservation.inbox_id
json.contact_id reservation.contact_id
json.contact_inbox_id reservation.contact_inbox_id
json.conversation_id reservation.conversation_id
json.suite_identifier reservation.suite_identifier
json.check_in_at reservation.check_in_at&.iso8601
json.check_out_at reservation.check_out_at&.iso8601
json.status reservation.status
json.metadata reservation.metadata
json.created_at reservation.created_at.to_i
json.updated_at reservation.updated_at.to_i
